name: 'Homework-02 CI'

on:
  push:
    branches:
      - homework-02

jobs:
  build-homework-02:
    if: github.ref == 'refs/heads/homework-02'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build .
      - run: cmake --build . --target test
      - run: cmake --build . --target package
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ip_filter-${{ github.run_number }}
          name: Homework-02 v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Generate big test output
        run: cat ip_filter.tsv | ./ip_filter >test_output.txt

      - name: Check test output
        run: md5sum -c test_output.md5

      - name: Upload Release Asset
        id: upload-release-asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ip_filter-0.0.${{ github.run_number }}-Linux.deb
          asset_name: ip_filter-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package
